### ISSUE TITLE
Doesn't work with _embedded

### ISSUE THREAD

**Issue by luandro** [elyobo/wp-rest-jmespath#1]
Congrats, this is an awesome project.

Is there any reason `_embedded` information doesn't show when queried with jmespath?

**Comment by elyobo** [comment]
Thanks, you're very kind - the credit really goes to the JMESPath people, this plugin is a very simple wrapper around their work.

With regards to the `_embedded` data..

The plugin hooks in to modify the response with the [`rest_post_dispatch`](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L334-L346) filter which they say "allows modification of the response before returning".  Unfortunately the `_embedded` structure is created _after_ that, so it's not available at the time that the filtering takes place.

To make things worse, the `rest_post_dispatch` filter is fired on [each embedded object too](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L578) too, so it's likely that the query would mess with them anyway.

There is one way I can see to work around this, but it seems a bit fragile.  The `rest_pre_serve_request` filter allows us to short circuit sending the response, so we could do that, copying [the code that sends the response](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/class-wp-rest-server.php#L377-L399) and _then_ do the filtering once the entire response (including `_embedded`) is ready to send.  It's fragile because we wouldn't pick up any changes to that code.

A better approach might be to nag the WP developers to add a filter that we can hook into to modify the result, like `rest_post_dispatch` is supposed to be, but including the `_embedded` data.

**Comment by luandro** [comment]
Thanks for the quick response. I guess it's too complicated, but that's all good to know. Cheers!

**Comment by elyobo** [comment]
No, it's not so complicated, I've just pushed up a branch you can try, `embedded-support`.  It detects when embedding was requested and follows a different approach (the fragile one described above) for that, but keeps the old, safer approach when embedding was not requested.

**Comment by luandro** [comment]
It worked, but it did break some other queries I was working with.

This works:

`wp-json/wp/v2/posts?_embed&filter[name]=blog-3&_query=[].{text:content.rendered,author:_embedded.author[0].name}`
 
This has stopped working:

`wp-json/wp/v2/pages?per_page=20&_query=[0:20].{title: title.rendered, slug: slug, text: content.rendered, custom: acf, image: better_featured_image.source_url }`

**Comment by elyobo** [comment]
Can you give me some more details about what's happening for the unembedded
example?

**Comment by elyobo** [comment]
Had a look, fixed in the branch now, please try again.

**Comment by elyobo** [comment]
@luandro Did the update work for you?

Also, FYI it looks like my suggestion of a new filter which allows a more robust solution to this [will be coming in a future WP version](https://core.trac.wordpress.org/ticket/38964).

**Comment by luandro** [comment]
Hey @elyobo,

just updated the plugin and `author:_embedded.author[0].name` has stopped working once again. I guess we'll have to wait for WP update?

Thanks a whole lot for the effort though 👍

**Comment by elyobo** [comment]
Are you sure you upgraded the branch and not master?  The branch is still working for embedded queries for me.

The WP update will make it easier, but I may keep this code in with version checks to support earlier WP versions.

**Comment by luandro** [comment]
Oh, forgot to change branches sorry.

It works perfectly, you're awesome. I guess it can be merged to master.

**Comment by elyobo** [comment]
Great, thanks for reporting this and helping to test @luandro

**Comment by elyobo** [comment]
The version in the official repos should be updated soon @luandro, so you can install from there or using wpackagist or whatever you're using.  If you're finding the plugin useful please leave the plugin a review on https://wordpress.org/plugins/wp-rest-jmespath/ as well!

**Comment by luandro** [comment]
Will do! Cheers!
