### ISSUE TITLE
Query other than slice?

### ISSUE THREAD

**Issue by stoconnor** [elyobo/wp-rest-jmespath#4]
Nice plugin, very handy instead of directly modifying the PHP for the info you want back I just add it to the query in the API call.

I am however having trouble with querying, is it possible to query other than the slice? e.g for title I've tried:
```
posts?_query=[title=="asd"].{id:id}
posts?_query=title[].[rendered=="asd"].{id:id}

```
for tags I've tried a number of things including:
`posts?_query=[tag=="other"].{id:id}`

Is this possible? Thanks in advance! 👍

**Comment by elyobo** [comment]
It looks like you're having trouble with the jmespath syntax, I recommend having a quick skim through [the jmespath site](http://jmespath.org/), they have some great interactive tutorials there.  I haven't been using it for a while but I had a quick brush up and can help you out.

With your specific examples you'd want to do something like

Posts with a rendered title of "asd"
>>> posts?_query=[?title.rendered=="asd"]

Posts tagged with "other"... if you have the ID of the tag it's pretty easy, because there's an array of the tag IDs (and you could get the ID by hitting the [tags endpoint](https://developer.wordpress.org/rest-api/reference/tags/#list-tags) first)
>>> posts?_query=[?contains(tags,'193')]

If you want to do it by name then it's going to get a bit more hairy, you need to enable embedding and query the embedded structure which is a bit noisy and I can't figure out how to do that match (probably something using `contains()` - maybe hit up the jmespath people if you can't figure that one out.
